### ISSUE TITLE
Newbie question: how to run py2puml in certain hierarchy?

### ISSUE THREAD

**Issue by Highlander1970** [lucsorel/py2puml#21]
I humbly apologize for an absolute newbie question, but I seem to be unable to get py2puml to produce any usable result (apart from empty "@startuml/@enduml"):

As a work in progress, I have following file structure:
C:\Folder_A\Folder_AA\Folder_Project\module1.py
C:\Folder_A\Folder_AA\Folder_Project\module2.py
C:\Folder_A\Folder_AA\Folder_Project\subfolder\module3.py 

What am I to enter into path and module parameters to get an output of all classes used in all three modules?

**Comment by lucsorel** [comment]
hello @huyz 

`py2puml project project` should work, but the library faces a module import error that I don't understand:

```
Traceback (most recent call last):
  File "/home/luc/Documents/repos/github/py2puml-test/.venv/bin/py2puml", line 8, in <module>
    sys.exit(run())
  File "/home/luc/Documents/repos/github/py2puml-test/.venv/lib/python3.8/site-packages/py2puml/cli.py", line 17, in run
    print(''.join(py2puml(args.path, args.module)))
  File "/home/luc/Documents/repos/github/py2puml-test/.venv/lib/python3.8/site-packages/py2puml/py2puml.py", line 17, in py2puml
    domain_item_module: ModuleType = import_module(name)
  File "/home/luc/.pyenv/versions/3.8.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'project'
```

Producing puml documentation for a root file (`root.py`) is not supported (it is not a recommended practice either)

**Comment by huyz** [comment]
> Is it the error you are facing?

Yes that's the error.  This is why I'm confused

**Comment by basilmusa** [comment]
Not working for me too. :|

**Comment by lucsorel** [comment]
hello @basilmusa 

I am sorry to read that the library does not work for you neither. Can you detail what your setup is (project structure, folders and files, the commands you tried), so that I can reproduce and investigate, if you please?

**Comment by ColtAllen** [comment]
I'm experiencing the same error as @huyz and @basilmusa when attempting to run `py2puml project_folder project_folder`  on an Ubuntu VM. Not sure if this is related, but when I run `py2puml` directly on a python module it outputs an empty UML script:
```
@startuml
@enduml
```

Can `py2puml` be ran on any folder containing python scripts, or do these scripts need to be compiled into a package?

**Comment by ColtAllen** [comment]
@lucsorel This issue crossed my mind again recently, and after looking through the Plant UML documentation, I think my problem is caused by the lack of class objects in the Python modules I'm using. Classes tend to be overkill for a lot of ML pipelines, but if PlantUML does not support the illustration of Python methods and the dependencies between them, I don't think this will be a viable documentation solution for any of my projects.

**Comment by lucsorel** [comment]
hello @ColtAllen 

Indeed, `py2puml` currently documents data structures (classes with static attributes or instance attributes defined in a constructor, dataclasses, namedtuple, enumerations). Someone proposed a pull request for documenting functions (#12, functions do not fit exactly as entities in the UML vision) but the author does not give signs of activity on it anymore :shrug:

**Comment by lucsorel** [comment]
hi @Highlander1970 @huyz @basilmusa :slightly_smiling_face: 

Please, forgive me for the long delay before solving this issue. It took me a while to understand how Python imports modules, specifically that Python uses the pathes listed in `sys.path`  to look for the modules to inspect. The current working directory is added when using poetry whereas it is not when using native virtual environments.

Would anyone of you be kind enough to review and approve #40 which fixes this issue, if you please?
 
The fix was short (see https://github.com/lucsorel/py2puml/pull/40/files#diff-7ff32e929e86cd812f60d9666a605c5b3d0a6cf13e938a4767ff538064e2b6c3R12) and a unit test checks that (https://github.com/lucsorel/py2puml/pull/40/files#diff-241c03bb18920b9ecd1bf42fd72007a92a4e08e44c95009d340ffb1fd0c3627dR31-R44).

As a maintainer, I appreciate to have the feedback of users (aside from adding issues :wink:). If you can't or don't have time, just let me know and I will validate the pull request myself.

**Comment by huyz** [comment]
I was able to get 0.7.2 to work on my simple example.

It's going to be a while until I can try it out on another full-blown project as I'm no longer working in Python at the moment.

Thanks for the fixes.

**Comment by lucsorel** [comment]
Thank you @huyz for your feedback. I am glad that #40 fixed this issue :smiley:
