### ISSUE TITLE
Package.py is not throw error.

### ISSUE THREAD

**Issue by Stampeiei** [lucsorel/py2puml#49]
Hi there,
I've tried the Pynguin to generated the test cases for Package.py
And there is one test case that mark as expected fail by Pynguin.
```
import pytest
import package as module_0
import dataclasses as module_1
@pytest.mark.xfail(strict=True)
def test_case_0():
    module_0.Package(123, [], 123)
```

And after tested with Pytest, it is throw the error that this case was mark as XPASS(Unexpected pass)

So I checked the Package.py function and found out that the there's no raise type error in there, that's why the Pynguin expected the test cases as failed.

```
from dataclasses import dataclass, field
from typing import List

@dataclass
class Package:
    '''A folder or a python module'''
    name: str
    children: List['Package'] = field(default_factory=list)
    items_number: int = 0
    # def __post_init__(self):
    #     if not isinstance(self.name, str):
    #         raise TypeError("Name must be a string.")    
    # suggestion #
    
```

Thank you.

**Comment by lucsorel** [comment]
I don't understand what you are trying to achieve. I am not going to change some code that works so that the unit test you generated could work as you expect.

If I wanted to enforce type validation of the attributes of an instance of `Package`, I would have used tools like pydantic to avoid writing all the `__post_init__` methods that you suggest.

Can you explain what your intentions were?
